### ISSUE TITLE
请教一下这是啥毛病，macos 13.1

### ISSUE THREAD

**Issue by DeakosS** [12425/wechat-exporter#7]
Traceback (most recent call last):
  File "/Users/*/Desktop/WeChatExport/WeChat_export.py", line 349, in iter_mbdb
    for f in next(os_walk(self._root))[1]:
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/*/Desktop/WeChatExport/WeChat_export.py", line 483, in <module>
    wechat.save_log()
  File "/Users/*/Desktop/WeChatExport/WeChat_export.py", line 435, in save_log
    for i, filename, messages, category in self.conversations:
  File "/Users/*/Desktop/WeChatExport/WeChat_export.py", line 398, in iter_conversation
    for i, (__, path, mm_db, chats_dbs, contacts_db) in enumerate(self.mmdb):
  File "/Users/*/Desktop/WeChatExport/WeChat_export.py", line 364, in iter_mmdb
    for db in self.mbdb:
RuntimeError: generator raised StopIteration

**Comment by DeakosS** [comment]
解决了，权限问题orz，经验证m1pro macos13.1+wechat8.0+ios16.0适用
